### ISSUE TITLE
Improvement: Additional parameter for the work files

### ISSUE THREAD

**Issue by Gill-Bates** [ddbnl/office365-audit-log-collector#31]
The collector needs four files in my configuration:
```
collector.log
config.yaml
known_content
known_logs
```

With the parameter `path` I can determine where the logs are stored, but not where the working files are placed.

```
log:
  path: "collector.log"
```

However, this path only applies to the log files. I would find it helpful if there was also a parameter to set the location of the working files. But that would mean a small redsign of the YAML structure. For instance:

```
path:
  log: "collector.log"
  workingdir: "/usr/local/o365collector"
```

**Comment by ddbnl** [comment]
There's no reason not to allow choosing the working dir and it would be a small effort to implement, I'll do that in the coming days. 

In order not to break backwards compatibility however I'll add the 'workingDir' parameter to the 'collect' section of the config, rather than moving the logging path parameter to a new section.

Thanks for the suggestion, makes a lot of sense :)

**Comment by ddbnl** [comment]
I was delayed a bit, but I've committed a new version that supports the working dir parameter. You can download the new executable [here](https://github.com/ddbnl/office365-audit-log-collector/raw/master/Linux/LINUX-OfficeAuditLogCollector-V2.3).

The parameter has an example in the new fullConfig.yaml. It looks like this:
```
collect:
  workingDir: /path/to/dir
```

I'll soon release an official release with all these latest changes and tag you in the credits for all the helpful suggestions, thanks!

**Comment by Gill-Bates** [comment]
Did you consider the logic, that the same path for collector.log is used, when no Log-Parameter ist specified?
