### ISSUE TITLE
Output to file not working?

### ISSUE THREAD

**Issue by sea-tee-hm** [ddbnl/office365-audit-log-collector#4]
Might be user issue - but I cannot seem to get the output to go to a file

**Comment by Sosti123** [comment]
Has anyone managed to get this working?

**Comment by furiel** [comment]
As far as I know file output does not work. There are two open pull requests that intend to address the issue.

What I did is: I created a branch that combines both pull requests into a single integration branch in my fork:
https://github.com/furiel/office365-audit-log-collector/commits/integration
that worked good enough for proof of concept purposes. That was quite a while ago though. Since then we switched to a c implementation. So I cannot tell if that code still works or not.

**Comment by ddbnl** [comment]
Fixed in beafb63.
